services:
  # A Docker web service
  - type: web
    name: vidburner_2.0
    repo: https://github.com/est-anime/vidburner_2.0
    runtime: node
    branch: main
    plan: free
    autoDeploy: true
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: Email
        value: false
      - key: APP_KEY
        sync: false
